# Explore here

In [197]:
# IMPORTS
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV

# PASO 1: PLANTEAMIENTO DEL PROBLEMA

- OBJETIVO: Crear un clasificador de reseñas de la tienda de Google Play.

In [198]:
# CARGAR EL DATASET

total_data = pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv")

total_data

package_name                                             review  \
0     com.facebook.katana   privacy at least put some option appear offli...   
1     com.facebook.katana   messenger issues ever since the last update, ...   
2     com.facebook.katana   profile any time my wife or anybody has more ...   
3     com.facebook.katana   the new features suck for those of us who don...   
4     com.facebook.katana   forced reload on uploading pic on replying co...   
..                    ...                                                ...   
886  com.rovio.angrybirds   loved it i loooooooooooooovvved it because it...   
887  com.rovio.angrybirds   all time legendary game the birthday party le...   
888  com.rovio.angrybirds   ads are way to heavy listen to the bad review...   
889  com.rovio.angrybirds   fun works perfectly well. ads aren't as annoy...   
890  com.rovio.angrybirds   they're everywhere i see angry birds everywhe...   

     polarity  
0           0  
1           0  
2           0  
3           0  
4           0  
..        ...  
886         1  
887         1  
888         0  
889         1  
890         1  

[891 rows x 3 columns]

# PASO 2: EXPLORACÓN Y LIMPIEZA DE DATOS

In [199]:
total_data.shape

(891, 3)

In [200]:
# OBTENER INFORMACIÓN SOBRE LOS TIPOS DE DATOS Y VALORES NO NULOS
total_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   package_name  891 non-null    object
 1   review        891 non-null    object
 2   polarity      891 non-null    int64 
dtypes: int64(1), object(2)
memory usage: 21.0+ KB


In [201]:
total_data.describe()

polarity
count  891.000000
mean     0.344557
std      0.475490
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000

In [202]:
print(total_data.isnull().sum())

package_name    0
review          0
polarity        0
dtype: int64


In [203]:
total_data.duplicated().sum()

np.int64(0)

ELIMINAR INFORMACIÓN IRRELEVANTE

In [204]:
total_data.drop(["package_name"], axis = 1, inplace = True)
total_data.head()

review  polarity
0   privacy at least put some option appear offli...         0
1   messenger issues ever since the last update, ...         0
2   profile any time my wife or anybody has more ...         0
3   the new features suck for those of us who don...         0
4   forced reload on uploading pic on replying co...         0

In [205]:
# Eliminar espacios y convertir a minúsculas el texto:
total_data["review"] = total_data["review"].str.strip().str.lower()

In [206]:
# Dividir el dataset en train y test: 
X = total_data["review"]
y = total_data["polarity"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 80)

X_train.head()

795    trust worthy as always! have been a long time ...
94     facebook ripoff used to see my connections new...
759    ads? really? ads in the kantipur app? you guys...
834    well done nicely designed .....this app had co...
113    groups??? ** edit: i changed my rating from on...
Name: review, dtype: object

In [207]:
# Transformar el texto en una matriz de recuento de palabras
vec_model = CountVectorizer(stop_words = "english")

X_train = vec_model.fit_transform(X_train).toarray()

X_test = vec_model.transform(X_test).toarray()

# PASO 3: Construye un Naive Bayes

In [208]:
# Inicialización y entrenamiento del modelo con GaussianNB

model_Gaussian = GaussianNB()
model_Gaussian.fit(X_train, y_train)

GaussianNB()

In [209]:
# Predicción del modelo con GaussianNB

y_pred = model_Gaussian.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1])

In [ ]:
# Probar el Accuracy del modelo GaussianNB

accuracy_score(y_test, y_pred)

0.776536312849162

In [211]:
# Inicialización y entrenamiento del modelo con MultinomialNB

model_multinomial = MultinomialNB()
model_multinomial.fit(X_train, y_train)

MultinomialNB()

In [212]:
# Predicción del modelo

y_pred = model_multinomial.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1])

In [213]:
# Probar el Accuracy del modelo

accuracy_score(y_test, y_pred)

0.8603351955307262

In [217]:
# Inicialización y entrenamiento del modelo con BernoulliNB

model_Bernoulli = BernoulliNB()
model_Bernoulli.fit(X_train, y_train)

BernoulliNB()

In [218]:
# Predicción del modelo con BernoulliNB

y_pred = model_Bernoulli.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0])

In [219]:
# Probar el Accuracy del modelo BernoulliNB

accuracy_score(y_test, y_pred)

0.7932960893854749

## Despues de probar con las tres implementaciones del Naive Bayes, procedemos a optimizar el modelo con la implementación que dió mejores resultados, es decir, MultinomialNB con un 0.86 de accuracy.

# Optimización del modelo

In [214]:
from sklearn.model_selection import GridSearchCV

hyperparams = {
    "alpha": np.linspace(0.01, 3.0, 200),
    "force_alpha": [True, False],
    "fit_prior": [True, False]    
}

model_multinomial = MultinomialNB()
grid = GridSearchCV(model_multinomial, hyperparams, scoring = "accuracy", cv = None)
grid

GridSearchCV(estimator=MultinomialNB(),
             param_grid={'alpha': array([0.01      , 0.02502513, 0.04005025, 0.05507538, 0.0701005 ,
       0.08512563, 0.10015075, 0.11517588, 0.13020101, 0.14522613,
       0.16025126, 0.17527638, 0.19030151, 0.20532663, 0.22035176,
       0.23537688, 0.25040201, 0.26542714, 0.28045226, 0.29547739,
       0.31050251, 0.32552764, 0.34055276, 0.35557789, 0.37060302,
       0.38562814, 0.400...
       2.56427136, 2.57929648, 2.59432161, 2.60934673, 2.62437186,
       2.63939698, 2.65442211, 2.66944724, 2.68447236, 2.69949749,
       2.71452261, 2.72954774, 2.74457286, 2.75959799, 2.77462312,
       2.78964824, 2.80467337, 2.81969849, 2.83472362, 2.84974874,
       2.86477387, 2.87979899, 2.89482412, 2.90984925, 2.92487437,
       2.9398995 , 2.95492462, 2.96994975, 2.98497487, 3.        ]),
                         'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='accuracy')

In [215]:
grid.fit(X_train, y_train)

GridSearchCV(estimator=MultinomialNB(),
             param_grid={'alpha': array([0.01      , 0.02502513, 0.04005025, 0.05507538, 0.0701005 ,
       0.08512563, 0.10015075, 0.11517588, 0.13020101, 0.14522613,
       0.16025126, 0.17527638, 0.19030151, 0.20532663, 0.22035176,
       0.23537688, 0.25040201, 0.26542714, 0.28045226, 0.29547739,
       0.31050251, 0.32552764, 0.34055276, 0.35557789, 0.37060302,
       0.38562814, 0.400...
       2.56427136, 2.57929648, 2.59432161, 2.60934673, 2.62437186,
       2.63939698, 2.65442211, 2.66944724, 2.68447236, 2.69949749,
       2.71452261, 2.72954774, 2.74457286, 2.75959799, 2.77462312,
       2.78964824, 2.80467337, 2.81969849, 2.83472362, 2.84974874,
       2.86477387, 2.87979899, 2.89482412, 2.90984925, 2.92487437,
       2.9398995 , 2.95492462, 2.96994975, 2.98497487, 3.        ]),
                         'fit_prior': [True, False],
                         'force_alpha': [True, False]},
             scoring='accuracy')

In [216]:
model_multinomial = MultinomialNB(force_alpha = True, alpha = 2.939899497487437, fit_prior = False)
model_multinomial.fit(X_train, y_train)
model_multinomial.fit(X_train, y_train)
y_pred = model_multinomial.predict(X_test)
accuracy_score(y_test, y_pred)

0.8715083798882681

In [221]:
from pickle import dump

ruta = "..\models/naive_bayes_force_alpha_True_alpha_2-93989949748_fit_prior_False_80.sav"
dump(model_multinomial, open(ruta, "wb"))

<>:3: SyntaxWarning: invalid escape sequence '\m'
<>:3: SyntaxWarning: invalid escape sequence '\m'
C:\Users\mafer\AppData\Local\Temp\ipykernel_10064\1849631842.py:3: SyntaxWarning: invalid escape sequence '\m'
  ruta = "..\models/naive_bayes_force_alpha_True_alpha_2-93989949748_fit_prior_False_80.sav"
